export const SUBJECT_NAMES: Readonly<Record<string, string>> = {
  ACT: "Accounting",
  AIE: "Artificial Intelligence",
  BIM: "Bioinformatics",
  BIO: "Biology",
  BMA: "Business Management and Analytics",
  BME: "Biomedical Engineering",
  CEC: "Civic Education",
  CHI: "Chinese",
  CHM: "Chemistry",
  CLC: "Chinese Language",
  CSC: "Computer Science",
  CSS: "Computational Social Science",
  DAI: "Digital and AI Literacy",
  DDA: "Data Science",
  DMS: "Decision and Management Sciences",
  ECE: "Electronic and Computer Engineering",
  ECO: "Economics",
  ENB: "English Studies",
  ENE: "Energy Engineering",
  ENG: "English",
  ENL: "English Language",
  ERG: "Engineering",
  FIN: "Finance",
  FMA: "Financial Mathematics",
  FRN: "French",
  FTE: "Financial Technology",
  GEA: "General Education A",
  GEB: "General Education B",
  GEC: "General Education C",
  GED: "General Education D",
  GFH: "In Dialogue with Humanity",
  GFN: "In Dialogue with Nature",
  GLB: "Global Studies",
  HSS: "Humanities and Social Sciences",
  IBA: "Integrated Business Administration",
  IDE: "Innovation and Entrepreneurship",
  ITE: "Information Technology",
  JPN: "Japanese",
  KOR: "Korean",
  LAW: "Law",
  LIN: "Linguistics",
  LIT: "Literature",
  MAT: "Mathematics",
  MED: "Medicine",
  MGT: "Management",
  MIS: "Management Information Systems",
  MKT: "Marketing",
  MSE: "Materials Science and Engineering",
  MUS: "Music",
  PED: "Physical Education",
  PHM: "Pharmacy",
  PHY: "Physics",
  PSY: "Psychology",
  SPN: "Spanish",
  STA: "Statistics",
  TRA: "Translation",
  URM: "Urban Management",
};

export function getSubjectName(subjectCode: string) {
  return SUBJECT_NAMES[subjectCode] ?? subjectCode;
}
